apiVersion: v1
kind: Service
metadata:
  name: it-website-service
  labels:
    app: it-website
spec:
  selector:
    app: it-website
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http

